spark:
  app_name: "EnergyLakehousePipeline"
  ui_enabled: "false"
  jars:
    packages: "org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.5.2,org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262"
  sql:
    extensions: "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions"
  
  # --- NETWORKS GLOBAL CREDENTIALS FOR MINIO ---
  hadoop:
    fs.s3a.endpoint: "http://minio:9000"
    fs.s3a.access.key: "minioadmin"
    fs.s3a.secret.key: "minioadminpassword"
    fs.s3a.path.style.access: "true"
    fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
    fs.s3a.connection.ssl.enabled: "false"
