spark:
  app_name: "EnergyLakehousePipeline"
  ui_enabled: "false"
  jars:
    packages: "org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.5.2"
  sql:
    extensions: "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions"
  catalog:
    local:
      class: "org.apache.iceberg.spark.SparkCatalog"
      type: "hadoop"
      warehouse: "/app/data_lakehouse/"